apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: spin
handler: spin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinygo-key-value-spin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinygo-key-value-spin
  template:
    metadata:
      labels:
        app: tinygo-key-value-spin
    spec:
      runtimeClassName: spin
      containers:
        - name: tinygo-key-value-spin
          image: felipecruz/tinygo-key-value:latest
          command: ["/"]
